// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  /* Custom Sidebar */
  tutorialSidebar: [
    'intro',
    'downloads',
    {
      type: 'category',
      label: '🚀 Project Showcase',
      items: [
        'showcase/mining',
        'showcase/superposition',
        'showcase/memory'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '📚 Fundamentals',
      items: [
        // If other docs exist, list them or use autogenerated
        { type: 'autogenerated', dirName: 'tutorial-basics' },
      ],
    },
  ],
};

export default sidebars;
